[package]
name = "ds-saver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
reqwest = "0.12.5"
serde_json = "1.0.113"
structopt = "0.3.26"
tokio = { version = "1.39.2", features = ["full"] }
